const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const DISPLAY_NOTIFICATION_DRAWER = "DISPLAY_NOTIFICATION_DRAWER";
const HIDE_NOTIFICATION_DRAWER = "HIDE_NOTIFICATION_DRAWER";
